<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Content Include="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <ProjectReference Include="..\ProjectIndexer.Core\ProjectIndexer.Core.csproj" />
  </ItemGroup>



  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

</Project>
